theme: jekyll-theme-slate
title: The homepage of Pier Francesco Sgargi, artist and nothing more.
description: What you will find here are projects, designs, thoughts.
plugins:
  - jemoji
url: "https://pier9670/GitHub.io"
markdown: kramdown
